![encabezado](./imagenes/encabezado.png)
# Universidad de Buenos Aires
## Laboratorio de Sistemas Embebidos
### Especialización en Inteligencia Artificial
#### Probabilidad y Estadística para la Inteligencia Artificial
**Docente**: Camilo Argoty

**Alumno**: Gaspar Acevedo Zain

**Código**: a2101

**Fecha**: 22/06/2025

## Enunciado

Siguiendo con la historia de Don Francisco, con el tiempo y gracias a los análisis de Matías, el pequeño comerciante de barrio cuenta hoy con 5 supermercados: ’Santa Ana’, ’La Floresta’, ’Los Cedros’, ’Palermo’ y ’Córdoba’.
También Matías ha avanzado en la Especialización en Inteligencia Artificial. Un día Don Francisco le plantea algunas inquietudes adicionales:
1. Don Francisco quiere entender mejor las ventas por mes del supermercado ’Santa Ana’.
2. Más aún, Don Francisco no sabe si puede estar seguro de que las ventas son las mismas en todos los supermercados o si hay alguno que se comporte mejor que los demás, y si alguna de las tiendas necesite más atención porque sus ventas
sean peores que los demás.

Con base en lo anterior,

## Carga del dataset

In [76]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np, scipy.stats as st
import statistics
import math

# Cargamos el archivo Excel
xls = pd.ExcelFile('../Datos_examen_final_21Co2025_a2101.xlsx')
# Creamos un dataframe a partir de cada Sheet en el Excel, representando las ventas de cada supermercado
df_santa_ana = pd.read_excel(xls, 'Santa Ana')
df_la_floresta = pd.read_excel(xls, 'La Floresta')
df_los_cedros = pd.read_excel(xls, 'Los Cedros')
df_palermo = pd.read_excel(xls, 'Palermo')
df_cordoba = pd.read_excel(xls, 'Córdoba')

In [77]:
# Agregamos el campo FechaMes a cada dataframe, representando el mes en que se realizó la venta en el determinado supermercado
df_santa_ana["FechaMes"] = df_santa_ana["Fecha"].dt.month
df_la_floresta["FechaMes"] = df_la_floresta["Fecha"].dt.month
df_los_cedros["FechaMes"] = df_los_cedros["Fecha"].dt.month
df_palermo["FechaMes"] = df_palermo["Fecha"].dt.month
df_cordoba["FechaMes"] = df_cordoba["Fecha"].dt.month

In [ ]:
# Definimos un objeto para obtener el nombre del mes a partir de su "índice"
nombre_meses = {
    1: "Enero", 2: "Febreo", 3: "Marzo", 4: "Abril",
    5: "Mayo", 6: "Junio", 7: "Julio", 8: "Agosto",
    9: "Septiembre", 10: "Octubre", 11: "Noviembre", 12: "Diciembre"
}

meses = []
for i in range(1, 13):
    meses.append(nombre_meses[i])

## Ejercicio número 1

### Enunciado Ejercicio número 1

(3 puntos) Determinen intervalos de confianza empíricos para el supermercado ’Santa Ana’ en cada mes, para significancias del 95% y el 99 %.

### Resolución Ejercicio número 1

Para determinar los intervalos de confianza empíricos para el supermercado `Santa Ana` en cada mes con significancias del 95% y 99%, debemos primero determinar los siguientes conceptos:

1. ¿Es un intervalo bilateral, unilateral superior, o unilateral inferior?
    1. Debido a que buscamos definir intervalos de confianza para las ventas de un supermercado dado, lo que nos interesa saber son los valores mínimos y máximos que pueden llegar a tener, motivo por el cual utilizaremos un `intervalo bilateral`.
1. ¿Qué distribución utilizar?
    1. Por un lado, no tenemos información de la media y varianza de la muestra, solamente tenemos observaciones, más precisamente, entre 30 y 31 observaciones por mes (a excepción de Febrero, que son 28), una por cada día.
    1. Por este motivo, como no tenemos información de la varianza, pero si tenemos más de 30 observaciones (salvo para el mes de Febrero), decidimos utilizar una distribución `Normal`, por lo cual, utilizaremos la media muestral y la varianza muestral para realizar el cálculo de nuestros intervalos de confianza.
    1. El motivo es que, si bien cuando no se conoce la varianza suele utilizarse una distribución `t-student`, como los tamaños de muestras son mayores a 30 para cada mes, la `t-student` suele comportarse como una `Normal`
1. A partir de los valores de significancia, ¿Cuál es el punto crítico de cada uno?
    1. Primero, definimos nuestros alfas de la siguiente manera: $p = 1 - \alpha$, siendo $p_{1} = 0.95$ y $p_{2} = 0.99$ para los respectivos niveles de significancia, quedando $\alpha_1 = 0.05$ y $\alpha_2 = 0.01$
    1. Ahora bien, a la hora de determinar los valores críticos para cada intervalo mediante una distribución `Normal`, como estamos usando un intervalo a dos colas, debemos dividir los alfa por dos, quedando: $\alpha_1 = 0.025$ y $\alpha_2 = 0.005$

Por lo dicho anteriormente, nuestros intervalos de confianza quedan definidos de la siguiente manera:

$P(\bar{x}-\frac{k^*\sigma}{\sqrt{n}}; \bar{x}+\frac{k^*\sigma}{\sqrt{n}})$

Siendo:
- $\bar{x}$ la media muestral, la cual calcularemos a partir de los datos dados
- $n$ el tamaño de la muestra
- $\sigma$ el desvío estandar, el cual calcularemos a partir de la varianza muestral $\sigma^{2}$
- $k^{*}$ o el valor crítico, el cual obtendremos mediante las tablas de la distribución `Normal` y los alfas definidos

A partir de los datos para el supermercado `Santa Ana` obtuvimos los siguientes intervaloes de confianza para cada mes, con niveles de significancia del 95% y 99%

### Respuestas Ejercicio número 1

#### Intervalo de confianza para el supermercado Santa Ana en cada mes, con un nivel de significancia del 95%

| | Intervalo (95%) | Límite Inferior | Límite Superior | Valor Crítico Utilizado |
| --- | --- | --- | --- | --- |
| Enero | (14984.78, 17025.30) | 14984.78 | 17025.30 | 1.96 |
| Febreo | (16881.18, 18695.46) | 16881.18 | 18695.46 | 1.96 |
| Marzo | (19396.03, 21328.12) | 19396.03 | 21328.12 | 1.96 |
| Abril | (18955.35, 21061.48) | 18955.35 | 21061.48 | 1.96 |
| Mayo | (19086.55, 21189.98) | 19086.55 | 21189.98 | 1.96 |
| Junio | (20789.06, 22626.40) | 20789.06 | 22626.40 | 1.96 |
| Julio | (18901.08, 21016.96) | 18901.08 | 21016.96 | 1.96 |
| Agosto | (20338.29, 22309.86) | 20338.29 | 22309.86 | 1.96 |
| Septiembre | (19943.70, 21884.34) | 19943.70 | 21884.34 | 1.96 |
| Octubre | (19696.96, 21635.42) | 19696.96 | 21635.42 | 1.96 |
| Noviembre | (21244.73, 22894.77) | 21244.73 | 22894.77 | 1.96 |
| Diciembre | (18641.23, 20086.08) | 18641.23 | 20086.08 | 1.96 |

#### Intervalo de confianza para el supermercado Santa Ana en cada mes, con un nivel de significancia del 99%

| | Intervalo (99%) | Límite Inferior | Límite Superior | Valor Crítico Utilizado |
| --- | --- | --- | --- | --- |
| Enero | (14664.19, 17345.88) | 14664.19 | 17345.88 | 2.576 |
| Febreo | (16596.14, 18980.51) | 16596.14 | 18980.51 | 2.576 |
| Marzo | (19092.48, 21631.67) | 19092.48 | 21631.67 | 2.576 |
| Abril | (18624.45, 21392.37) | 18624.45 | 21392.37 | 2.576 |
| Mayo | (18756.08, 21520.45) | 18756.08 | 21520.45 | 2.576 |
| Junio | (20500.40, 22915.07) | 20500.40 | 22915.07 | 2.576 |
| Julio | (18568.65, 21349.39) | 18568.65 | 21349.39 | 2.576 |
| Agosto | (20028.53, 22619.62) | 20028.53 | 22619.62 | 2.576 |
| Septiembre | (19638.80, 22189.24) | 19638.80 | 22189.24 | 2.576 |
| Octubre | (19392.40, 21939.97) | 19392.40 | 21939.97 | 2.576 |
| Noviembre | (20985.49, 23154.01) | 20985.49 | 23154.01 | 2.576 |
| Diciembre | (18414.23, 20313.09) | 18414.23 | 20313.09 | 2.576 |

### Código para la resolución del Ejercicio número 1

In [126]:
# Esta función nos permite obtener un intervalod de confianza a partir de tres datos:
# datos: las observaciones en sí
# nivel de confianza: el nivel de confianza, expresado en decimales
# bilateral: es el intervalo bilateral, o no?
def intervalo_confianza(datos, nivel_de_confianza, bilateral = True):
    alfa = 1 - nivel_de_confianza
    if bilateral:
        alfa = alfa/2

    varianza_muestral = statistics.variance(datos) # utiliza el denominador (N-1)
    desvio_muestral = math.sqrt(varianza_muestral)
    media_muestral = statistics.mean(datos)
    raiz_n = math.sqrt(len(datos))
    k = st.norm.ppf(1-alfa)

    intervalo_valor_izq = media_muestral - k*desvio_muestral/raiz_n
    intervalo_valor_der = media_muestral + k*desvio_muestral/raiz_n

    return intervalo_valor_izq, intervalo_valor_der, k

In [152]:
columnas_95=["Intervalo (95%)", "Limite_Inferior", "Limite_Superior", "Valor_Critico Utilizado"]
columnas_99=["Intervalo (99%)", "Limite_Inferior", "Limite_Superior", "Valor_Critico Utilizado"]
df_95 = pd.DataFrame(index=meses, columns=columnas_95)
df_99 = pd.DataFrame(index=meses, columns=columnas_99)

In [154]:
for i in range(1,13):
    df_por_mes = df_santa_ana[df_santa_ana["FechaMes"] == i]
    data = df_por_mes.Ventas

    nivel_confianza_01 = 0.95
    nivel_confianza_02 = 0.99

    limite_inferior_095, limite_superior_095, k_095 = intervalo_confianza(data, nivel_confianza_01, True)
    limite_inferior_099, limite_superior_099, k_099 = intervalo_confianza(data, nivel_confianza_02, True)

    df_95.loc[nombre_meses[i]] = [f"({round(limite_inferior_095, 2)}, {round(limite_superior_095, 2)})", round(limite_inferior_095, 2), round(limite_superior_095, 2), round(k_095, 2)]
    df_99.loc[nombre_meses[i]] = [f"({round(limite_inferior_099, 2)}, {round(limite_superior_099, 2)})", round(limite_inferior_099, 2), round(limite_superior_099, 2), round(k_099, 3)]

In [155]:
display(df_95)
display(df_99)

,Intervalo (95%),Limite_Inferior,Limite_Superior,Valor_Critico Utilizado
Enero,"(14984.78, 17025.3)",14984.78,17025.3,1.96
Febreo,"(16881.18, 18695.46)",16881.18,18695.46,1.96
Marzo,"(19396.03, 21328.12)",19396.03,21328.12,1.96
Abril,"(18955.35, 21061.48)",18955.35,21061.48,1.96
Mayo,"(19086.55, 21189.98)",19086.55,21189.98,1.96
Junio,"(20789.06, 22626.4)",20789.06,22626.4,1.96
Julio,"(18901.08, 21016.96)",18901.08,21016.96,1.96
Agosto,"(20338.29, 22309.86)",20338.29,22309.86,1.96
Septiembre,"(19943.7, 21884.34)",19943.7,21884.34,1.96
Octubre,"(19696.96, 21635.42)",19696.96,21635.42,1.96
Noviembre,"(21244.73, 22894.77)",21244.73,22894.77,1.96
Diciembre,"(18641.23, 20086.08)",18641.23,20086.08,1.96

,Intervalo (99%),Limite_Inferior,Limite_Superior,Valor_Critico Utilizado
Enero,"(14664.19, 17345.88)",14664.19,17345.88,2.576
Febreo,"(16596.14, 18980.51)",16596.14,18980.51,2.576
Marzo,"(19092.48, 21631.67)",19092.48,21631.67,2.576
Abril,"(18624.45, 21392.37)",18624.45,21392.37,2.576
Mayo,"(18756.08, 21520.45)",18756.08,21520.45,2.576
Junio,"(20500.4, 22915.07)",20500.4,22915.07,2.576
Julio,"(18568.65, 21349.39)",18568.65,21349.39,2.576
Agosto,"(20028.53, 22619.62)",20028.53,22619.62,2.576
Septiembre,"(19638.8, 22189.24)",19638.8,22189.24,2.576
Octubre,"(19392.4, 21939.97)",19392.4,21939.97,2.576
Noviembre,"(20985.49, 23154.01)",20985.49,23154.01,2.576
Diciembre,"(18414.23, 20313.09)",18414.23,20313.09,2.576