![encabezado](./imagenes/encabezado.png)
# Universidad de Buenos Aires
## Laboratorio de Sistemas Embebidos
### Especialización en Inteligencia Artificial
#### Probabilidad y Estadística para la Inteligencia Artificial
**Docente**: Camilo Argoty

**Alumno**: Gaspar Acevedo Zain

**Código**: a2101

**Fecha**: 22/06/2025

## Enunciado

Siguiendo con la historia de Don Francisco, con el tiempo y gracias a los análisis de Matías, el pequeño comerciante de barrio cuenta hoy con 5 supermercados: ’Santa Ana’, ’La Floresta’, ’Los Cedros’, ’Palermo’ y ’Córdoba’.
También Matías ha avanzado en la Especialización en Inteligencia Artificial. Un día Don Francisco le plantea algunas inquietudes adicionales:
1. Don Francisco quiere entender mejor las ventas por mes del supermercado ’Santa Ana’.
2. Más aún, Don Francisco no sabe si puede estar seguro de que las ventas son las mismas en todos los supermercados o si hay alguno que se comporte mejor que los demás, y si alguna de las tiendas necesite más atención porque sus ventas
sean peores que los demás.

Con base en lo anterior,

## Carga del dataset

In [ ]:
import pandas as pd
import scipy.stats as st
import statistics
import math
from scipy.stats import f_oneway

# Cargamos el archivo Excel
xls = pd.ExcelFile('../Datos_examen_final_21Co2025_a2101.xlsx')
# Creamos un dataframe a partir de cada Sheet en el Excel,
# representando las ventas de cada supermercado
df_santa_ana = pd.read_excel(xls, 'Santa Ana')
df_la_floresta = pd.read_excel(xls, 'La Floresta')
df_los_cedros = pd.read_excel(xls, 'Los Cedros')
df_palermo = pd.read_excel(xls, 'Palermo')
df_cordoba = pd.read_excel(xls, 'Córdoba')

In [ ]:
# Agregamos el campo FechaMes a cada dataframe, representando
# el mes en que se realizó la venta en el determinado supermercado
df_santa_ana["FechaMes"] = df_santa_ana["Fecha"].dt.month
df_la_floresta["FechaMes"] = df_la_floresta["Fecha"].dt.month
df_los_cedros["FechaMes"] = df_los_cedros["Fecha"].dt.month
df_palermo["FechaMes"] = df_palermo["Fecha"].dt.month
df_cordoba["FechaMes"] = df_cordoba["Fecha"].dt.month

In [ ]:
# Definimos un objeto para obtener el nombre del mes a partir de su "índice"
nombre_meses = {
    1: "Enero", 2: "Febreo", 3: "Marzo", 4: "Abril",
    5: "Mayo", 6: "Junio", 7: "Julio", 8: "Agosto",
    9: "Septiembre", 10: "Octubre", 11: "Noviembre", 12: "Diciembre"
}

meses = []
for i in range(1, 13):
    meses.append(nombre_meses[i])

## Ejercicio número 1

### Enunciado Ejercicio número 1

(3 puntos) Determinen intervalos de confianza empíricos para el supermercado ’Santa Ana’ en cada mes, para significancias del 95% y el 99 %.

### Resolución Ejercicio número 1

Para determinar los intervalos de confianza empíricos para el supermercado `Santa Ana` en cada mes con significancias del 95% y 99%, debemos primero determinar los siguientes conceptos:

1. ¿Es un intervalo bilateral, unilateral superior, o unilateral inferior?
    1. Debido a que buscamos definir intervalos de confianza para las ventas de un supermercado dado, lo que nos interesa saber son los valores mínimos y máximos que pueden llegar a tener, motivo por el cual utilizaremos un `intervalo bilateral`.
1. ¿Qué distribución utilizar?
    1. Por un lado, no tenemos información de la media y varianza de la muestra, solamente tenemos observaciones, más precisamente, entre 30 y 31 observaciones por mes (a excepción de Febrero, que son 28), una por cada día.
    1. Por este motivo, como no tenemos información de la varianza, pero si tenemos más de 30 observaciones (salvo para el mes de Febrero), decidimos utilizar una distribución `Normal`, por lo cual, utilizaremos la media muestral y la varianza muestral para realizar el cálculo de nuestros intervalos de confianza.
    1. El motivo es que, si bien cuando no se conoce la varianza suele utilizarse una distribución `t-student`, como los tamaños de muestras son mayores a 30 para cada mes, la `t-student` suele comportarse como una `Normal`
1. A partir de los valores de significancia, ¿Cuál es el punto crítico de cada uno?
    1. Primero, definimos nuestros alfas de la siguiente manera: $p = 1 - \alpha$, siendo $p_{1} = 0.95$ y $p_{2} = 0.99$ para los respectivos niveles de significancia, quedando $\alpha_1 = 0.05$ y $\alpha_2 = 0.01$
    1. Ahora bien, a la hora de determinar los valores críticos para cada intervalo mediante una distribución `Normal`, como estamos usando un intervalo a dos colas, debemos dividir los alfa por dos, quedando: $\alpha_1 = 0.025$ y $\alpha_2 = 0.005$

Por lo dicho anteriormente, nuestros intervalos de confianza quedan definidos de la siguiente manera:

$P(\bar{x}-\frac{k^*\sigma}{\sqrt{n}}; \bar{x}+\frac{k^*\sigma}{\sqrt{n}})$

Siendo:
- $\bar{x}$ la media muestral, la cual calcularemos a partir de los datos dados
- $n$ el tamaño de la muestra
- $\sigma$ el desvío estandar, el cual calcularemos a partir de la varianza muestral $\sigma^{2}$
- $k^{*}$ o el valor crítico, el cual obtendremos mediante las tablas de la distribución `Normal` y los alfas definidos

A partir de los datos para el supermercado `Santa Ana` obtuvimos los siguientes intervaloes de confianza para cada mes, con niveles de significancia del 95% y 99%

### Respuestas Ejercicio número 1

#### Intervalo de confianza para el supermercado Santa Ana en cada mes, con un nivel de significancia del 95%

| | Intervalo (95%) | Límite Inferior | Límite Superior | Valor Crítico Utilizado |
| --- | --- | --- | --- | --- |
| Enero | (14984.78, 17025.30) | 14984.78 | 17025.30 | 1.96 |
| Febreo | (16881.18, 18695.46) | 16881.18 | 18695.46 | 1.96 |
| Marzo | (19396.03, 21328.12) | 19396.03 | 21328.12 | 1.96 |
| Abril | (18955.35, 21061.48) | 18955.35 | 21061.48 | 1.96 |
| Mayo | (19086.55, 21189.98) | 19086.55 | 21189.98 | 1.96 |
| Junio | (20789.06, 22626.40) | 20789.06 | 22626.40 | 1.96 |
| Julio | (18901.08, 21016.96) | 18901.08 | 21016.96 | 1.96 |
| Agosto | (20338.29, 22309.86) | 20338.29 | 22309.86 | 1.96 |
| Septiembre | (19943.70, 21884.34) | 19943.70 | 21884.34 | 1.96 |
| Octubre | (19696.96, 21635.42) | 19696.96 | 21635.42 | 1.96 |
| Noviembre | (21244.73, 22894.77) | 21244.73 | 22894.77 | 1.96 |
| Diciembre | (18641.23, 20086.08) | 18641.23 | 20086.08 | 1.96 |

#### Intervalo de confianza para el supermercado Santa Ana en cada mes, con un nivel de significancia del 99%

| | Intervalo (99%) | Límite Inferior | Límite Superior | Valor Crítico Utilizado |
| --- | --- | --- | --- | --- |
| Enero | (14664.19, 17345.88) | 14664.19 | 17345.88 | 2.576 |
| Febreo | (16596.14, 18980.51) | 16596.14 | 18980.51 | 2.576 |
| Marzo | (19092.48, 21631.67) | 19092.48 | 21631.67 | 2.576 |
| Abril | (18624.45, 21392.37) | 18624.45 | 21392.37 | 2.576 |
| Mayo | (18756.08, 21520.45) | 18756.08 | 21520.45 | 2.576 |
| Junio | (20500.40, 22915.07) | 20500.40 | 22915.07 | 2.576 |
| Julio | (18568.65, 21349.39) | 18568.65 | 21349.39 | 2.576 |
| Agosto | (20028.53, 22619.62) | 20028.53 | 22619.62 | 2.576 |
| Septiembre | (19638.80, 22189.24) | 19638.80 | 22189.24 | 2.576 |
| Octubre | (19392.40, 21939.97) | 19392.40 | 21939.97 | 2.576 |
| Noviembre | (20985.49, 23154.01) | 20985.49 | 23154.01 | 2.576 |
| Diciembre | (18414.23, 20313.09) | 18414.23 | 20313.09 | 2.576 |

### Código para la resolución del Ejercicio número 1

In [201]:
# Esta función nos permite obtener un
# intervalo de confianza a partir de tres datos:
# datos: las observaciones en sí
# nivel de confianza: el nivel de confianza, expresado en decimales
# bilateral: es el intervalo bilateral, o no?
def intervalo_confianza(datos, nivel_de_confianza, bilateral = True):
    alfa = 1 - nivel_de_confianza
    if bilateral:
        alfa = alfa/2

    varianza_muestral = statistics.variance(datos) # utiliza el denominador (N-1)
    desvio_muestral = math.sqrt(varianza_muestral)
    media_muestral = statistics.mean(datos)
    raiz_n = math.sqrt(len(datos))
    k = st.norm.ppf(1-alfa)

    intervalo_valor_izq = media_muestral - k*desvio_muestral/raiz_n
    intervalo_valor_der = media_muestral + k*desvio_muestral/raiz_n

    return intervalo_valor_izq, intervalo_valor_der, k

In [202]:
columnas_95=["Intervalo (95%)", "Limite_Inferior",
             "Limite_Superior", "Valor_Critico Utilizado"]
columnas_99=["Intervalo (99%)", "Limite_Inferior",
             "Limite_Superior", "Valor_Critico Utilizado"]
df_95 = pd.DataFrame(index=meses, columns=columnas_95)
df_99 = pd.DataFrame(index=meses, columns=columnas_99)

In [207]:
for i in range(1,13):
    df_por_mes = df_santa_ana[df_santa_ana["FechaMes"] == i]
    data = df_por_mes.Ventas

    nivel_confianza_01 = 0.95
    nivel_confianza_02 = 0.99

    li_095, ls_095, k_095 = intervalo_confianza(data, nivel_confianza_01, True)
    li_099, ls_099, k_099 = intervalo_confianza(data, nivel_confianza_02, True)

    df_95.loc[nombre_meses[i]] = [f"({round(li_095, 2)}, {round(ls_095, 2)})",
                                  round(li_095, 2),
                                  round(ls_095, 2),
                                  round(k_095, 2)]
    df_99.loc[nombre_meses[i]] = [f"({round(li_099, 2)}, {round(ls_099, 2)})",
                                  round(li_099, 2),
                                  round(ls_099, 2),
                                  round(k_099, 3)]

In [208]:
display(df_95)
display(df_99)

,Intervalo (95%),Limite_Inferior,Limite_Superior,Valor_Critico Utilizado
Enero,"(14984.78, 17025.3)",14984.78,17025.3,1.96
Febreo,"(16881.18, 18695.46)",16881.18,18695.46,1.96
Marzo,"(19396.03, 21328.12)",19396.03,21328.12,1.96
Abril,"(18955.35, 21061.48)",18955.35,21061.48,1.96
Mayo,"(19086.55, 21189.98)",19086.55,21189.98,1.96
Junio,"(20789.06, 22626.4)",20789.06,22626.4,1.96
Julio,"(18901.08, 21016.96)",18901.08,21016.96,1.96
Agosto,"(20338.29, 22309.86)",20338.29,22309.86,1.96
Septiembre,"(19943.7, 21884.34)",19943.7,21884.34,1.96
Octubre,"(19696.96, 21635.42)",19696.96,21635.42,1.96
Noviembre,"(21244.73, 22894.77)",21244.73,22894.77,1.96
Diciembre,"(18641.23, 20086.08)",18641.23,20086.08,1.96

,Intervalo (99%),Limite_Inferior,Limite_Superior,Valor_Critico Utilizado
Enero,"(14664.19, 17345.88)",14664.19,17345.88,2.576
Febreo,"(16596.14, 18980.51)",16596.14,18980.51,2.576
Marzo,"(19092.48, 21631.67)",19092.48,21631.67,2.576
Abril,"(18624.45, 21392.37)",18624.45,21392.37,2.576
Mayo,"(18756.08, 21520.45)",18756.08,21520.45,2.576
Junio,"(20500.4, 22915.07)",20500.4,22915.07,2.576
Julio,"(18568.65, 21349.39)",18568.65,21349.39,2.576
Agosto,"(20028.53, 22619.62)",20028.53,22619.62,2.576
Septiembre,"(19638.8, 22189.24)",19638.8,22189.24,2.576
Octubre,"(19392.4, 21939.97)",19392.4,21939.97,2.576
Noviembre,"(20985.49, 23154.01)",20985.49,23154.01,2.576
Diciembre,"(18414.23, 20313.09)",18414.23,20313.09,2.576

## Ejercicio número 2

### Enunciado Ejercicio número 2

(4 puntos) Realicen pruebas ANOVA para determinar si las ventas esperadas de todas las tiendas son iguales o no, con significancia del 95%

### Resolución Ejercicio número 2

#### Paso 01 - Planteo de la hipótesis

En este caso, se nos plantea determinar si las ventas esperadas de todas las tiendas son iguales o no, es decir, podemos definir las siguientes hipótesis

$H_{0}: $ Todas las medias de las ventas esperadas para las distintas tiendas son iguales 

$H_{1}: $ Al menos una de las tiendas tiene una media de las ventas esperadas distintas a las demás

Dicho de otra manera, planteamos

$H_{0}: \mu_{Santa Ana} = \mu_{La Floresta} = \mu_{Los Cedros} = \mu_{Palermo} = \mu_{Cordoba}$

$H_{1}: $ al menos una igualdad no es cierta

Además, como nos piden una significancia del 95%, podemos definir:

$\alpha = 0.05$

#### Paso 02 - Definimos el estadístico de contraste

El estadístico se basará en una $F$ de Fisher con $t-1$ y $n-t$ grados de libertad para la varianza entre grupos o $SS_{factores}$ y la varianza intra grupos o $SS_{error}$ respectivamente, quedando:

$F = \frac{\frac{SS_{factores}}{t-1}}{\frac{SS_{error}}{n-t}}$

siendo:
- $t$: la cantidad de tiendas distintas, es decir $t = 5$
- $n$: la cantidad de observaciones, siendo $ n = 365 * 5 = 1825$

Es decir, tenemos:
- $t -1 = 5 -1 = 4 = v_{1}$
- $n - t = 1825 - 5 = 1820 = v_{2}$
- $\alpha = 0.05$

Por lo tanto, nuestro punto crítico para no aceptar $H_{0}$ será el siguiente (ver sección `Código para la resolución del Ejercicio número 2`):

- $Punto Crítico = 2.38$

Por lo tanto, si nuestro estadístico $F$ es mayor a dicho Punto Crítico, estaremos en la situación de ***No Aceptar*** $H_{0}$.

#### Paso 03 - Realizamos el test de Anova

En este paso, realizaremos el test de ANOVA de una sola vía o `One Way` mediante código de Python. El código correspondiente puede observarse en la sección `Código para la resolución del Ejercicio número 2`.

Como resultado, obtuvimos lo siguiente:

- Estadístico $F = 30.012$
- P-valor $= 3.2655108240630393e-24$

Hay dos formas de evaluar dichos resultados, ambas dando como resultado el rechazo de la $H_{0}$:

1. Como el estadístico $F = 30.012$ es mayor a nuestro $Punto Crítico = 2.38$, estamos en zona de rechazo de la $H_{0}$
1. Como el P-valor $= 3.2655108240630393e-24$ es menor (mucho menor incluso) que nuestro $\alpha = 0.05$, estamos ante la situación de rechazar la $H_{0}$

#### Paso 04 - Conclusión

Hemos realizado un test de ANOVA para analizar con un nivel de significancia del $95%$ con las siguientes hipótesis:

$H_{0}: \mu_{Santa Ana} = \mu_{La Floresta} = \mu_{Los Cedros} = \mu_{Palermo} = \mu_{Cordoba}$

$H_{1}: $ al menos una igualdad no es cierta


Al calcular el punto crítico para los siguientes valores:

- $t - 1 = 4 = v_{1}$
- $n - t = 1820 = v_{2}$
- $\alpha = 0.05$

Obtuvimos que $Punto Crítico = 2.38$

Y al realizar el ANOVA utilizando nuestro estadístico $F$ (F de Fisher) con los datos mencionados anteriormente, obtuvimos que:

- Estadístico $F = 30.012$
- P-valor $= 3.2655108240630393e-24$

A partir de los datos, definimos que:

- Estadístico $F = 30.012$ es mayor que $Punto Crítico = 2.38$, por lo cual estamos en zona de rechazo de $H_{0}$
- P-valor $= 3.2655108240630393e-24$ es menor que $\alpha = 0.05$, por lo cual estamos en zona de rechazo de $H_{0}$

Es decir, tenemos evidencia suficiente para rechazar la `Hipótesis Nula` $H_{0}$ que suponía que las ventas esperadas de todas las tiendas son iguales (siendo las tiendas Santa Ana, La Floresta, Los Cedros, Palermo, y Córdoba), lo cual indica que por lo menos alguna de las ventas esperadas de las tiendas es distintas a las demás.

### Código para la resolución del Ejercicio número 2

In [212]:
# Esta función nos devuelve el punto crítico para:
# alfa = 0.05 (significancia 0.95)
# v1 = t - 1 = 4
# v2 = n - t = 1820
pto_critico_anova = st.f.ppf(0.95, 4, 1820)

print(f"Punto crítico para ANOVA, con:")
print(f"\talfa = 0.05")
print(f"\tv1 = 4")
print(f"\tv2 = 1820")
print(f"\tPunto crítico: {round(pto_critico_anova, 2)}")

Punto crítico para ANOVA, con:
	alfa = 0.05
	v1 = 4
	v2 = 1820
	Punto crítico: 2.38

In [211]:
# El siguiente código nos devuelve el resultado de
# ANOVA sobre nuestros dataset de interés,
# más precisamente devuelve:
# El estadístico F (en nuestro caso, f_statistic_anova)
# El p-valor asociado (en nuestro caso, p_value_anova)
f_statistic_anova, p_value_anova = f_oneway(df_santa_ana.Ventas, 
                                            df_la_floresta.Ventas,
                                            df_los_cedros.Ventas,
                                            df_palermo.Ventas,
                                            df_cordoba.Ventas)

print(f"Estadístico F: {round(f_statistic_anova, 3)}")
print(f"P-valor: {p_value_anova}")

Estadístico F: 30.012
P-valor: 3.2655108240630393e-24

## Ejercicio número 3

### Enunciado Ejercicio número 3

(3 puntos) Identifiquen la tienda con mayor promedio de ventas y la tienda con menor promedio de ventas y realicen una prueba de hipótesis para determinar si la diferencia entre ellas es distinta de cero o no.

### Resolución Ejercicio número 3

#### Paso 01 - Definimos las tiendas con menor y mayor promedio

Comenzamos encontrando las tiendas que tienen el menor y mayor promedio de ventas, las cuales son (ver sección `Código para la resolución del Ejercicio número 3`):

- Menor promedio de ventas: La Floresta, con $18820.34$
- Mayor promedio de ventas: Córdoba, con $21002.06$

Ya definidas las tiendas a analizar, definamos nuestro ensayo de hipótesis:

#### Paso 02 - Definimos nuestras Hipótesis Nula y Alternativa

Nos interesa saber si la diferencia entre los valores de ventas promedios de ambas tiendas son distintos de cero, lo cual nos permite definir nuestra *Hipótesis de Investigación*, la cual es:

>"La diferencia de las ventas promedio del supermercado Floresta y el supermercado Córdoba son distintos de cero"

Esto puede expresarse matemáticamente como:

$\mu_{Floresta} - \mu_{Cordoba} \neq 0$

o como

$\mu_{Floresta} \neq \mu_{Cordoba}$

Lo cual representa a nuestra Hipótesis alternativa $H_1$.

De esta forma, nuestras Hipótesis nula $H_0$ e Hipótesis alternativa $H_1$ quedan definidas de esta forma:

$H_{0}: \mu_{Floresta} = \mu_{Cordoba}$

$H_{1}: \mu_{Floresta} \neq \mu_{Cordoba}$

#### Paso 03 - Definimos el tipo de Prueba y el intervalo de confianza

Respecto al intervalo de confianza, como el ejercicio no nos da información, asumimos un valor del 95%, es decir, un $\alpha = 0.05$.
Además, debemos realizar una prueba `Bilateral`, ya que nuestras Hipótesis Nula y Alternativa están definidas en función de igual/desigualdad de medias.

Por último, respecto a las varianzas poblacionales, como no tenemos información (en el enunciado) asumimos que son ***diferentes***.

#### Paso 04 - Definimos nuestro estadístico de Prueba

Considerando que estamos en un caso donde nuestro test de hipótesis se basa en la diferencia de medias, con varianzas desconocidas y (asumidas) diferentes, nuestro estadístico de Prueba sería el siguente:

$t' = \frac{(\bar{x}_{Floresta}-\bar{x}_{Cordoba})-(\mu_{Floresta}-\mu_{Cordoba})}{\sqrt{\frac{s_{Floresta}^{2}}{n_{Floresta}} + \frac{s_{Cordoba}^{2}}{n_{Cordoba}}}}$

Siendo:

- $\bar{x}_{Floresta}$ la media muestral del supermercado Floresta
- $\bar{x}_{Cordoba}$ la media muestral del supermercado Cordoba
- $(\mu_{Floresta}-\mu_{Cordoba})$ la diferencia de nuestras medias, en la hipótesis nula, para la cual es cero, ya que definimos $H_{0}: \mu_{Floresta} = \mu_{Cordoba}$
- $s_{Floresta}^{2}$ varianza de las ventas del supermercado Floresta
- $s_{Cordoba}^{2}$ varianza de las ventas del supermercado Cordoba
- $n_{Floresta}$ tamaño de la muestra de Floresta
- $n_{Cordoba}$ tamaño de la muestra de Cordoba

Los valores para cada uno de ellos son (nota: puede encontrar el cálculo en la sección `Código para la resolución del Ejercicio número 3`):

- $\bar{x}_{Floresta} = 18820.34$ 
- $\bar{x}_{Cordoba} = 21002.06$
- $(\mu_{Floresta}-\mu_{Cordoba}) = 0$
- $s_{Floresta}^{2} = 10006564.71$
- $s_{Cordoba}^{2} = 8390917.89$
- $n_{Floresta} = 365$
- $n_{Cordoba} = 365$

Por lo que nuestro estadístico $t'$ queda definido como:

$t'= -9.72$

#### Paso 05 - Definimos los grados de libertad

Para el test de hipótesis definido, nuestros grados de libertad se determinan mediante la siguiente fórmula:

$v = \frac{(\frac{S_{Floresta}^2}{n_{Floresta}} + \frac{S_{Cordoba}^2}{n_{Cordoba}})^{2}}{\frac{(\frac{S_{Floresta}^2}{n_{Floresta}})^2}{n_{Floresta}-1}+\frac{(\frac{S_{Cordoba}^2}{n_{Cordoba}})^2}{n_{Cordoba}-1}}$

Como se puede observar en la sección `Código para la resolución del Ejercicio número 3`, los grados de libertad para nuestro test de hipótesis son:

$v = 722$

#### Paso 06 - Definimos la zona de rechazo

Como estamos en un test de hipótesis bilateral, debemos dividir nuestro alfa entre dos, quedando:

$\alpha_{2} = 0.025$

A partir del *alfa* definido y de los grados de libertad $v=722$ definidos anteriormente, obtenemos el valor crítico de $\pm 1.96$ (el cálculo se puede ver en la sección de `Código para la resolución del Ejercicio número 3`)

De esta forma, definimos nuestras zonas de rechazo como:

- $t' < - t_{\alpha/2}$ o $t' > t_{\alpha/2}$

Como nuestro estadístico $t'$ es negativo, utilizamos la primer zona de rechazo:

- $t' < - t_{\alpha/2}$

Dado que:

- $t' = -9.72$
- $ - t_{\alpha/2} = -1.96$

Tenemos que:

- $-9.72 < -1.96$

Por lo tanto, si se rechaza la `Hipótesis Nula` $H_{0}: \mu_{Floresta} = \mu_{Cordoba}$

#### Paso 07 - Definimos el valor de P

Al ser una prueba bilateral, debemos utilizar la fórmula dada por:

$P = 2(p(t\ge|t'|))$

Es decir:

$P = 2(p(t\ge|-9.72|))$

A partir de las cuentas realizadas en la sección de `Código para la resolución del Ejercicio número 3` obtenemos que:

$P = 4.531578487153108e-21$

Considerando nuestro $\alpha = 0.5$ tenemos que $P < \alpha$, por lo cuál podemos afirmar que `Si se rechaza la Hipótesis Nula` $H_{0}: \mu_{Floresta} = \mu_{Cordoba}$.

#### Paso 08 - Conclusión

Existe suficiente evidencia estadística para determinar que la media de las ventas del supermercado "La Floresta" es significativamente diferente a la media de las ventas del supermercado "Córdoba", es decir, que `la diferencia de las ventas promedio del supermercado Floresta y el supermercado Córdoba SI son distintos de cero` ($P = 4.531578487153108e-21$)

### Código para la resolución del Ejercicio número 3

In [210]:
# Comparación de medias de cada supermercado
media_santa_ana = statistics.mean(df_santa_ana.Ventas)
media_la_floresta = statistics.mean(df_la_floresta.Ventas)
media_los_cedros = statistics.mean(df_los_cedros.Ventas)
media_palermo = statistics.mean(df_palermo.Ventas)
media_cordoba = statistics.mean(df_cordoba.Ventas)

print(f"Promedio Ventas supermercado Santa Ana: {round(media_santa_ana, 2)}")
print(f"Promedio Ventas supermercado La Floresta: {round(media_la_floresta, 2)}")
print(f"Promedio Ventas supermercado Los Cedros: {round(media_los_cedros, 2)}")
print(f"Promedio Ventas supermercado Palermo: {round(media_palermo, 2)}")
print(f"Promedio Ventas supermercado Córdoba: {round(media_cordoba, 2)}")

Promedio Ventas supermercado Santa Ana: 20031.34
Promedio Ventas supermercado La Floresta: 18820.34
Promedio Ventas supermercado Los Cedros: 19983.36
Promedio Ventas supermercado Palermo: 18996.42
Promedio Ventas supermercado Córdoba: 21002.06

In [214]:
# Cálculo de estadístico t'

media_muestral_la_floresta = statistics.mean(df_la_floresta.Ventas)
media_muestral_cordoba = statistics.mean(df_cordoba.Ventas)
tamano_muestra_la_floresta = len(df_la_floresta.Ventas)
tamano_muestra_cordoba = len(df_cordoba.Ventas)
varianza_muestral_la_floresta = statistics.variance(df_la_floresta.Ventas)
varianza_muestral_cordoba = statistics.variance(df_cordoba.Ventas)

estadistico_t = (media_muestral_la_floresta - media_muestral_cordoba)/math.sqrt(
    (varianza_muestral_la_floresta/tamano_muestra_la_floresta)+
    (varianza_muestral_cordoba/tamano_muestra_cordoba))

print(f"Supermercado \"La Floresta\"")
print(f"\tTamaño muestral: {tamano_muestra_la_floresta}")
print(f"\tMedia muestral: {round(media_muestral_la_floresta, 2)}")
print(f"\tVarianza muestral: {round(varianza_muestral_la_floresta, 2)}")

print(f"Supermercado \"Córdoba\":")
print(f"\tTamaño muestral: {tamano_muestra_cordoba}")
print(f"\tMedia muestral: {round(media_muestral_cordoba, 2)}")
print(f"\tVarianza muestral: {round(varianza_muestral_cordoba, 2)}")
print(f"Estadístico t': {round(estadistico_t, 2)}")

Supermercado "La Floresta"
	Tamaño muestral: 365
	Media muestral: 18820.34
	Varianza muestral: 10006564.71
Supermercado "Córdoba":
	Tamaño muestral: 365
	Media muestral: 21002.06
	Varianza muestral: 8390917.89
Estadístico t': -9.72

In [218]:
# Cálculo de grados de libertad

varianza_dividido_media_la_floresta = varianza_muestral_la_floresta/tamano_muestra_la_floresta
varianza_dividido_media_cordoba = varianza_muestral_cordoba/tamano_muestra_cordoba

grados_de_libertad_numerador = (
    varianza_dividido_media_la_floresta + varianza_dividido_media_cordoba
    )**2
grados_de_libertad_denominador = (
    (varianza_dividido_media_la_floresta**2)/(tamano_muestra_la_floresta-1)) + (
        (varianza_dividido_media_cordoba**2)/(tamano_muestra_cordoba-1))

grados_de_libertad = grados_de_libertad_numerador/grados_de_libertad_denominador

print(f"Grados de Libertad: {math.floor(grados_de_libertad)}")

Grados de Libertad: 722

In [219]:
# Obtenemos el valor crítico para nuestra t-student
# con alfa=0.025 y grados de libertad = 722
valor_critico = st.t.ppf(0.025, 722)

print(f"Valor crítico para alfa= 0.025" + 
      "y Grados de Libertad=722: {round(valor_critico, 2)}")

Valor crítico para alfa= 0.025y Grados de Libertad=722: {round(valor_critico, 2)}

In [220]:
st.t.cdf(-9.72, 722)*2

np.float64(4.531578487153108e-21)